# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/kria_k260.xdc

# Block Designs: C:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ButtonTest.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ButtonTest || ORIG_REF_NAME==ButtonTest} -quiet] -quiet

# IP: C:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_zynq_ultra_ps_e_0_1/ButtonTest_zynq_ultra_ps_e_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ButtonTest_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==ButtonTest_zynq_ultra_ps_e_0_1} -quiet] -quiet

# IP: C:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_clk_wiz_0_0/ButtonTest_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ButtonTest_clk_wiz_0_0 || ORIG_REF_NAME==ButtonTest_clk_wiz_0_0} -quiet] -quiet

# IP: C:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_axi_gpio_0_0/ButtonTest_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ButtonTest_axi_gpio_0_0 || ORIG_REF_NAME==ButtonTest_axi_gpio_0_0} -quiet] -quiet

# IP: C:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_xbar_0/ButtonTest_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ButtonTest_xbar_0 || ORIG_REF_NAME==ButtonTest_xbar_0} -quiet] -quiet

# IP: C:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_auto_ds_0/ButtonTest_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ButtonTest_auto_ds_0 || ORIG_REF_NAME==ButtonTest_auto_ds_0} -quiet] -quiet

# IP: C:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_auto_pc_0/ButtonTest_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ButtonTest_auto_pc_0 || ORIG_REF_NAME==ButtonTest_auto_pc_0} -quiet] -quiet

# IP: C:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_auto_ds_1/ButtonTest_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ButtonTest_auto_ds_1 || ORIG_REF_NAME==ButtonTest_auto_ds_1} -quiet] -quiet

# IP: C:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_auto_pc_1/ButtonTest_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ButtonTest_auto_pc_1 || ORIG_REF_NAME==ButtonTest_auto_pc_1} -quiet] -quiet

# IP: C:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_ps8_0_axi_periph_0/ButtonTest_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ButtonTest_ps8_0_axi_periph_0 || ORIG_REF_NAME==ButtonTest_ps8_0_axi_periph_0} -quiet] -quiet

# IP: C:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_rst_ps8_0_99M_0/ButtonTest_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ButtonTest_rst_ps8_0_99M_0 || ORIG_REF_NAME==ButtonTest_rst_ps8_0_99M_0} -quiet] -quiet

# XDC: C:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ButtonTest_ooc.xdc
