# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/Keyboard/Keyboard.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Keyboard || ORIG_REF_NAME==Keyboard} -quiet] -quiet

# IP: bd/Keyboard/ip/Keyboard_processing_system7_0_0/Keyboard_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Keyboard_processing_system7_0_0 || ORIG_REF_NAME==Keyboard_processing_system7_0_0} -quiet] -quiet

# IP: bd/Keyboard/ip/Keyboard_ps7_0_axi_periph_0/Keyboard_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Keyboard_ps7_0_axi_periph_0 || ORIG_REF_NAME==Keyboard_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Keyboard/ip/Keyboard_rst_clk_100M_0/Keyboard_rst_clk_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Keyboard_rst_clk_100M_0 || ORIG_REF_NAME==Keyboard_rst_clk_100M_0} -quiet] -quiet

# IP: bd/Keyboard/ip/Keyboard_AXI_PS2_Keyboard_0_0/Keyboard_AXI_PS2_Keyboard_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Keyboard_AXI_PS2_Keyboard_0_0 || ORIG_REF_NAME==Keyboard_AXI_PS2_Keyboard_0_0} -quiet] -quiet

# IP: bd/Keyboard/ip/Keyboard_ila_0_0/Keyboard_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Keyboard_ila_0_0 || ORIG_REF_NAME==Keyboard_ila_0_0} -quiet] -quiet

# IP: bd/Keyboard/ip/Keyboard_edgedetector_0_0/Keyboard_edgedetector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Keyboard_edgedetector_0_0 || ORIG_REF_NAME==Keyboard_edgedetector_0_0} -quiet] -quiet

# IP: bd/Keyboard/ip/Keyboard_auto_pc_0/Keyboard_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Keyboard_auto_pc_0 || ORIG_REF_NAME==Keyboard_auto_pc_0} -quiet] -quiet

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/FPGA_Imp/VivadoPrjs/Zybo_Keyboard/Zybo_Keyboard.gen/sources_1/bd/Keyboard/ip/Keyboard_processing_system7_0_0/Keyboard_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Keyboard_processing_system7_0_0 || ORIG_REF_NAME==Keyboard_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/FPGA_Imp/VivadoPrjs/Zybo_Keyboard/Zybo_Keyboard.gen/sources_1/bd/Keyboard/ip/Keyboard_rst_clk_100M_0/Keyboard_rst_clk_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Keyboard_rst_clk_100M_0 || ORIG_REF_NAME==Keyboard_rst_clk_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/FPGA_Imp/VivadoPrjs/Zybo_Keyboard/Zybo_Keyboard.gen/sources_1/bd/Keyboard/ip/Keyboard_rst_clk_100M_0/Keyboard_rst_clk_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Keyboard_rst_clk_100M_0 || ORIG_REF_NAME==Keyboard_rst_clk_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/FPGA_Imp/VivadoPrjs/Zybo_Keyboard/Zybo_Keyboard.gen/sources_1/bd/Keyboard/ip/Keyboard_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Keyboard_ila_0_0 || ORIG_REF_NAME==Keyboard_ila_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/FPGA_Imp/VivadoPrjs/Zybo_Keyboard/Zybo_Keyboard.gen/sources_1/bd/Keyboard/ip/Keyboard_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Keyboard_ila_0_0 || ORIG_REF_NAME==Keyboard_ila_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/FPGA_Imp/VivadoPrjs/Zybo_Keyboard/Zybo_Keyboard.gen/sources_1/bd/Keyboard/ip/Keyboard_ila_0_0/Keyboard_ila_0_0_ooc.xdc

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/FPGA_Imp/VivadoPrjs/Zybo_Keyboard/Zybo_Keyboard.gen/sources_1/bd/Keyboard/ip/Keyboard_auto_pc_0/Keyboard_auto_pc_0_ooc.xdc

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/FPGA_Imp/VivadoPrjs/Zybo_Keyboard/Zybo_Keyboard.gen/sources_1/bd/Keyboard/Keyboard_ooc.xdc
