# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Tutorial.xdc

# Block Designs: bd/Tutorial/Tutorial.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Tutorial || ORIG_REF_NAME==Tutorial} -quiet] -quiet

# IP: bd/Tutorial/ip/Tutorial_zynq_ultra_ps_e_0_0/Tutorial_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Tutorial_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==Tutorial_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/Tutorial/ip/Tutorial_axi_gpio_0_0/Tutorial_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Tutorial_axi_gpio_0_0 || ORIG_REF_NAME==Tutorial_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Tutorial/ip/Tutorial_xbar_0/Tutorial_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Tutorial_xbar_0 || ORIG_REF_NAME==Tutorial_xbar_0} -quiet] -quiet

# IP: bd/Tutorial/ip/Tutorial_auto_ds_0/Tutorial_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Tutorial_auto_ds_0 || ORIG_REF_NAME==Tutorial_auto_ds_0} -quiet] -quiet

# IP: bd/Tutorial/ip/Tutorial_auto_pc_0/Tutorial_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Tutorial_auto_pc_0 || ORIG_REF_NAME==Tutorial_auto_pc_0} -quiet] -quiet

# IP: bd/Tutorial/ip/Tutorial_auto_ds_1/Tutorial_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Tutorial_auto_ds_1 || ORIG_REF_NAME==Tutorial_auto_ds_1} -quiet] -quiet

# IP: bd/Tutorial/ip/Tutorial_auto_pc_1/Tutorial_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Tutorial_auto_pc_1 || ORIG_REF_NAME==Tutorial_auto_pc_1} -quiet] -quiet

# IP: bd/Tutorial/ip/Tutorial_ps8_0_axi_periph_0/Tutorial_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Tutorial_ps8_0_axi_periph_0 || ORIG_REF_NAME==Tutorial_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/Tutorial/ip/Tutorial_rst_ps8_0_96M_0/Tutorial_rst_ps8_0_96M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Tutorial_rst_ps8_0_96M_0 || ORIG_REF_NAME==Tutorial_rst_ps8_0_96M_0} -quiet] -quiet

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Tutorial/Tutorial.gen/sources_1/bd/Tutorial/Tutorial_ooc.xdc
