#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Nov 17 04:15:17 EST 2022
# SW Build 3605665 on Fri Aug  5 22:52:02 MDT 2022
#
# IP Build 3603185 on Sat Aug  6 04:07:44 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim AXI_PS2_Keyboard_v1_0_behav -key {Behavioral:sim_1:Functional:AXI_PS2_Keyboard_v1_0} -tclbatch AXI_PS2_Keyboard_v1_0.tcl -view /home/cekp/Desktop/GitHub/SeniorCapstone/FPGA_Imp/VivadoPrjs/Zybo_Keyboard/Zybo_Keyboard.tmp/AXI_PS2_Keyboard_v1_0_project/AXI_PS2_Keyboard_v1_0_behav.wcfg -log simulate.log"
xsim AXI_PS2_Keyboard_v1_0_behav -key {Behavioral:sim_1:Functional:AXI_PS2_Keyboard_v1_0} -tclbatch AXI_PS2_Keyboard_v1_0.tcl -view /home/cekp/Desktop/GitHub/SeniorCapstone/FPGA_Imp/VivadoPrjs/Zybo_Keyboard/Zybo_Keyboard.tmp/AXI_PS2_Keyboard_v1_0_project/AXI_PS2_Keyboard_v1_0_behav.wcfg -log simulate.log

