# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/BTN_LED_Linux/BTN_LED_Linux.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_Linux || ORIG_REF_NAME==BTN_LED_Linux} -quiet] -quiet

# IP: bd/BTN_LED_Linux/ip/BTN_LED_Linux_zynq_ultra_ps_e_0_0/BTN_LED_Linux_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_Linux_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==BTN_LED_Linux_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/BTN_LED_Linux/ip/BTN_LED_Linux_axi_gpio_1_0/BTN_LED_Linux_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_Linux_axi_gpio_1_0 || ORIG_REF_NAME==BTN_LED_Linux_axi_gpio_1_0} -quiet] -quiet

# IP: bd/BTN_LED_Linux/ip/BTN_LED_Linux_axi_timer_0_0/BTN_LED_Linux_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_Linux_axi_timer_0_0 || ORIG_REF_NAME==BTN_LED_Linux_axi_timer_0_0} -quiet] -quiet

# IP: bd/BTN_LED_Linux/ip/BTN_LED_Linux_axi_timer_1_0/BTN_LED_Linux_axi_timer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_Linux_axi_timer_1_0 || ORIG_REF_NAME==BTN_LED_Linux_axi_timer_1_0} -quiet] -quiet

# IP: bd/BTN_LED_Linux/ip/BTN_LED_Linux_xbar_0/BTN_LED_Linux_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_Linux_xbar_0 || ORIG_REF_NAME==BTN_LED_Linux_xbar_0} -quiet] -quiet

# IP: bd/BTN_LED_Linux/ip/BTN_LED_Linux_ps8_0_axi_periph_0/BTN_LED_Linux_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_Linux_ps8_0_axi_periph_0 || ORIG_REF_NAME==BTN_LED_Linux_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/BTN_LED_Linux/ip/BTN_LED_Linux_rst_ps8_0_99M_0/BTN_LED_Linux_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_Linux_rst_ps8_0_99M_0 || ORIG_REF_NAME==BTN_LED_Linux_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/BTN_LED_Linux/ip/BTN_LED_Linux_auto_ds_0/BTN_LED_Linux_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_Linux_auto_ds_0 || ORIG_REF_NAME==BTN_LED_Linux_auto_ds_0} -quiet] -quiet

# IP: bd/BTN_LED_Linux/ip/BTN_LED_Linux_auto_pc_0/BTN_LED_Linux_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_Linux_auto_pc_0 || ORIG_REF_NAME==BTN_LED_Linux_auto_pc_0} -quiet] -quiet

# IP: bd/BTN_LED_Linux/ip/BTN_LED_Linux_auto_ds_1/BTN_LED_Linux_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_Linux_auto_ds_1 || ORIG_REF_NAME==BTN_LED_Linux_auto_ds_1} -quiet] -quiet

# IP: bd/BTN_LED_Linux/ip/BTN_LED_Linux_auto_pc_1/BTN_LED_Linux_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_Linux_auto_pc_1 || ORIG_REF_NAME==BTN_LED_Linux_auto_pc_1} -quiet] -quiet

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/Milestone3.gen/sources_1/bd/BTN_LED_Linux/BTN_LED_Linux_ooc.xdc
