# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_auto_ds_1/ButtonTest_auto_ds_1.xci
# IP: The module: 'ButtonTest_auto_ds_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_auto_ds_1/ButtonTest_auto_ds_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ButtonTest_auto_ds_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_auto_ds_1/ButtonTest_auto_ds_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ButtonTest_auto_ds_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_auto_ds_1/ButtonTest_auto_ds_1.xci
# IP: The module: 'ButtonTest_auto_ds_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_auto_ds_1/ButtonTest_auto_ds_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ButtonTest_auto_ds_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_auto_ds_1/ButtonTest_auto_ds_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ButtonTest_auto_ds_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
