# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/Milestone3.srcs/sources_1/bd/BTN_LED_Linux/ip/BTN_LED_Linux_auto_ds_1/BTN_LED_Linux_auto_ds_1.xci
# IP: The module: 'BTN_LED_Linux_auto_ds_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/Milestone3.gen/sources_1/bd/BTN_LED_Linux/ip/BTN_LED_Linux_auto_ds_1/BTN_LED_Linux_auto_ds_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'BTN_LED_Linux_auto_ds_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/Milestone3.gen/sources_1/bd/BTN_LED_Linux/ip/BTN_LED_Linux_auto_ds_1/BTN_LED_Linux_auto_ds_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BTN_LED_Linux_auto_ds_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/Milestone3.srcs/sources_1/bd/BTN_LED_Linux/ip/BTN_LED_Linux_auto_ds_1/BTN_LED_Linux_auto_ds_1.xci
# IP: The module: 'BTN_LED_Linux_auto_ds_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/Milestone3.gen/sources_1/bd/BTN_LED_Linux/ip/BTN_LED_Linux_auto_ds_1/BTN_LED_Linux_auto_ds_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'BTN_LED_Linux_auto_ds_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/Milestone3.gen/sources_1/bd/BTN_LED_Linux/ip/BTN_LED_Linux_auto_ds_1/BTN_LED_Linux_auto_ds_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BTN_LED_Linux_auto_ds_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
