# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Tutorial/Tutorial.srcs/sources_1/bd/Tutorial/ip/Tutorial_zynq_ultra_ps_e_0_0/Tutorial_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'Tutorial_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Tutorial/Tutorial.gen/sources_1/bd/Tutorial/ip/Tutorial_zynq_ultra_ps_e_0_0/Tutorial_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Tutorial_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Tutorial/Tutorial.gen/sources_1/bd/Tutorial/ip/Tutorial_zynq_ultra_ps_e_0_0/Tutorial_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Tutorial_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Tutorial/Tutorial.srcs/sources_1/bd/Tutorial/ip/Tutorial_zynq_ultra_ps_e_0_0/Tutorial_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'Tutorial_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Tutorial/Tutorial.gen/sources_1/bd/Tutorial/ip/Tutorial_zynq_ultra_ps_e_0_0/Tutorial_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Tutorial_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Tutorial/Tutorial.gen/sources_1/bd/Tutorial/ip/Tutorial_zynq_ultra_ps_e_0_0/Tutorial_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Tutorial_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
