# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Tutorial/Tutorial.srcs/sources_1/bd/Tutorial/ip/Tutorial_rst_ps8_0_96M_0/Tutorial_rst_ps8_0_96M_0.xci
# IP: The module: 'Tutorial_rst_ps8_0_96M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Tutorial/Tutorial.gen/sources_1/bd/Tutorial/ip/Tutorial_rst_ps8_0_96M_0/Tutorial_rst_ps8_0_96M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Tutorial_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Tutorial/Tutorial.gen/sources_1/bd/Tutorial/ip/Tutorial_rst_ps8_0_96M_0/Tutorial_rst_ps8_0_96M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Tutorial_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Tutorial/Tutorial.gen/sources_1/bd/Tutorial/ip/Tutorial_rst_ps8_0_96M_0/Tutorial_rst_ps8_0_96M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Tutorial_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Tutorial/Tutorial.srcs/sources_1/bd/Tutorial/ip/Tutorial_rst_ps8_0_96M_0/Tutorial_rst_ps8_0_96M_0.xci
# IP: The module: 'Tutorial_rst_ps8_0_96M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Tutorial/Tutorial.gen/sources_1/bd/Tutorial/ip/Tutorial_rst_ps8_0_96M_0/Tutorial_rst_ps8_0_96M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Tutorial_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Tutorial/Tutorial.gen/sources_1/bd/Tutorial/ip/Tutorial_rst_ps8_0_96M_0/Tutorial_rst_ps8_0_96M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Tutorial_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Tutorial/Tutorial.gen/sources_1/bd/Tutorial/ip/Tutorial_rst_ps8_0_96M_0/Tutorial_rst_ps8_0_96M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Tutorial_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
