# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraint.xdc

# Block Designs: bd/BTN_LED/BTN_LED.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED || ORIG_REF_NAME==BTN_LED} -quiet] -quiet

# IP: bd/BTN_LED/ip/BTN_LED_btn_to_led_0_0/BTN_LED_btn_to_led_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_btn_to_led_0_0 || ORIG_REF_NAME==BTN_LED_btn_to_led_0_0} -quiet] -quiet

# IP: bd/BTN_LED/ip/BTN_LED_btn_to_led_clk_0_0/BTN_LED_btn_to_led_clk_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_btn_to_led_clk_0_0 || ORIG_REF_NAME==BTN_LED_btn_to_led_clk_0_0} -quiet] -quiet

# IP: bd/BTN_LED/ip/BTN_LED_clk_wiz_0/BTN_LED_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_clk_wiz_0 || ORIG_REF_NAME==BTN_LED_clk_wiz_0} -quiet] -quiet

# IP: bd/BTN_LED/ip/BTN_LED_zynq_ultra_ps_e_0_1/BTN_LED_zynq_ultra_ps_e_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==BTN_LED_zynq_ultra_ps_e_0_1} -quiet] -quiet

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/VivadoPrjs/PL_BTN_LED/PL_BTN_LED.gen/sources_1/bd/BTN_LED/BTN_LED_ooc.xdc
