#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Nov 26 05:33:57 EST 2022
# SW Build 3605665 on Fri Aug  5 22:52:02 MDT 2022
#
# IP Build 3603185 on Sat Aug  6 04:07:44 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim System_wrapper_behav -key {Behavioral:sim_1:Functional:System_wrapper} -tclbatch System_wrapper.tcl -protoinst "protoinst_files/System.protoinst" -log simulate.log"
xsim System_wrapper_behav -key {Behavioral:sim_1:Functional:System_wrapper} -tclbatch System_wrapper.tcl -protoinst "protoinst_files/System.protoinst" -log simulate.log

