# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_axi_gpio_0_0/ButtonTest_axi_gpio_0_0.xci
# IP: The module: 'ButtonTest_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_axi_gpio_0_0/ButtonTest_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ButtonTest_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_axi_gpio_0_0/ButtonTest_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ButtonTest_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_axi_gpio_0_0/ButtonTest_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ButtonTest_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_axi_gpio_0_0/ButtonTest_axi_gpio_0_0.xci
# IP: The module: 'ButtonTest_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_axi_gpio_0_0/ButtonTest_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ButtonTest_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_axi_gpio_0_0/ButtonTest_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ButtonTest_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/spixy/Documents/00_Github/SeniorCapstone/Milestone3/BlockDesigns/ButtonTest/ButtonTest/ip/ButtonTest_axi_gpio_0_0/ButtonTest_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ButtonTest_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
