# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/VivadoPrjs/ConstraintFiles/Zybo_Imp.xdc

# Block Designs: bd/Imp/Imp.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Imp || ORIG_REF_NAME==Imp} -quiet] -quiet

# IP: bd/Imp/ip/Imp_processing_system7_0_0/Imp_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Imp_processing_system7_0_0 || ORIG_REF_NAME==Imp_processing_system7_0_0} -quiet] -quiet

# IP: bd/Imp/ip/Imp_axi_gpio_0_0/Imp_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Imp_axi_gpio_0_0 || ORIG_REF_NAME==Imp_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Imp/ip/Imp_axi_gpio_1_0/Imp_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Imp_axi_gpio_1_0 || ORIG_REF_NAME==Imp_axi_gpio_1_0} -quiet] -quiet

# IP: bd/Imp/ip/Imp_axi_gpio_0_1/Imp_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Imp_axi_gpio_0_1 || ORIG_REF_NAME==Imp_axi_gpio_0_1} -quiet] -quiet

# IP: bd/Imp/ip/Imp_axi_gpio_3_0/Imp_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Imp_axi_gpio_3_0 || ORIG_REF_NAME==Imp_axi_gpio_3_0} -quiet] -quiet

# IP: bd/Imp/ip/Imp_xbar_1/Imp_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Imp_xbar_1 || ORIG_REF_NAME==Imp_xbar_1} -quiet] -quiet

# IP: bd/Imp/ip/Imp_ps7_0_axi_periph_1/Imp_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Imp_ps7_0_axi_periph_1 || ORIG_REF_NAME==Imp_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/Imp/ip/Imp_rst_sysclk_100Mhz_100M_0/Imp_rst_sysclk_100Mhz_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Imp_rst_sysclk_100Mhz_100M_0 || ORIG_REF_NAME==Imp_rst_sysclk_100Mhz_100M_0} -quiet] -quiet

# IP: bd/Imp/ip/Imp_I2C_LCD_Transmitter_1_0/Imp_I2C_LCD_Transmitter_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Imp_I2C_LCD_Transmitter_1_0 || ORIG_REF_NAME==Imp_I2C_LCD_Transmitter_1_0} -quiet] -quiet

# IP: bd/Imp/ip/Imp_auto_pc_0/Imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Imp_auto_pc_0 || ORIG_REF_NAME==Imp_auto_pc_0} -quiet] -quiet

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/VivadoPrjs/Zybo_Imp/Zybo_Imp.gen/sources_1/bd/Imp/ip/Imp_processing_system7_0_0/Imp_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Imp_processing_system7_0_0 || ORIG_REF_NAME==Imp_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/VivadoPrjs/Zybo_Imp/Zybo_Imp.gen/sources_1/bd/Imp/ip/Imp_axi_gpio_0_0/Imp_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Imp_axi_gpio_0_0 || ORIG_REF_NAME==Imp_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/VivadoPrjs/Zybo_Imp/Zybo_Imp.gen/sources_1/bd/Imp/ip/Imp_axi_gpio_0_0/Imp_axi_gpio_0_0_ooc.xdc

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/VivadoPrjs/Zybo_Imp/Zybo_Imp.gen/sources_1/bd/Imp/ip/Imp_axi_gpio_0_0/Imp_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Imp_axi_gpio_0_0 || ORIG_REF_NAME==Imp_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/VivadoPrjs/Zybo_Imp/Zybo_Imp.gen/sources_1/bd/Imp/ip/Imp_axi_gpio_1_0/Imp_axi_gpio_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Imp_axi_gpio_1_0 || ORIG_REF_NAME==Imp_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/VivadoPrjs/Zybo_Imp/Zybo_Imp.gen/sources_1/bd/Imp/ip/Imp_axi_gpio_1_0/Imp_axi_gpio_1_0_ooc.xdc

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/VivadoPrjs/Zybo_Imp/Zybo_Imp.gen/sources_1/bd/Imp/ip/Imp_axi_gpio_1_0/Imp_axi_gpio_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Imp_axi_gpio_1_0 || ORIG_REF_NAME==Imp_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/VivadoPrjs/Zybo_Imp/Zybo_Imp.gen/sources_1/bd/Imp/ip/Imp_axi_gpio_0_1/Imp_axi_gpio_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Imp_axi_gpio_0_1 || ORIG_REF_NAME==Imp_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/VivadoPrjs/Zybo_Imp/Zybo_Imp.gen/sources_1/bd/Imp/ip/Imp_axi_gpio_0_1/Imp_axi_gpio_0_1_ooc.xdc

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/VivadoPrjs/Zybo_Imp/Zybo_Imp.gen/sources_1/bd/Imp/ip/Imp_axi_gpio_0_1/Imp_axi_gpio_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Imp_axi_gpio_0_1 || ORIG_REF_NAME==Imp_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/VivadoPrjs/Zybo_Imp/Zybo_Imp.gen/sources_1/bd/Imp/ip/Imp_axi_gpio_3_0/Imp_axi_gpio_3_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Imp_axi_gpio_3_0 || ORIG_REF_NAME==Imp_axi_gpio_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/VivadoPrjs/Zybo_Imp/Zybo_Imp.gen/sources_1/bd/Imp/ip/Imp_axi_gpio_3_0/Imp_axi_gpio_3_0_ooc.xdc

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/VivadoPrjs/Zybo_Imp/Zybo_Imp.gen/sources_1/bd/Imp/ip/Imp_axi_gpio_3_0/Imp_axi_gpio_3_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Imp_axi_gpio_3_0 || ORIG_REF_NAME==Imp_axi_gpio_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/VivadoPrjs/Zybo_Imp/Zybo_Imp.gen/sources_1/bd/Imp/ip/Imp_rst_sysclk_100Mhz_100M_0/Imp_rst_sysclk_100Mhz_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Imp_rst_sysclk_100Mhz_100M_0 || ORIG_REF_NAME==Imp_rst_sysclk_100Mhz_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/VivadoPrjs/Zybo_Imp/Zybo_Imp.gen/sources_1/bd/Imp/ip/Imp_rst_sysclk_100Mhz_100M_0/Imp_rst_sysclk_100Mhz_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Imp_rst_sysclk_100Mhz_100M_0 || ORIG_REF_NAME==Imp_rst_sysclk_100Mhz_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/VivadoPrjs/Zybo_Imp/Zybo_Imp.gen/sources_1/bd/Imp/ip/Imp_auto_pc_0/Imp_auto_pc_0_ooc.xdc

# XDC: /home/cekp/Desktop/GitHub/SeniorCapstone/VivadoPrjs/Zybo_Imp/Zybo_Imp.gen/sources_1/bd/Imp/Imp_ooc.xdc
